# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVCXm8dcvWQbZW-FA9P7gDvArV7Qe_FX
"""

!pip install pandas numpy scikit-learn nltk

!mv train[1].csv train.csv
!mv test[1].csv test.csv

!ls

!mkdir -p news_classification_project/data/raw
!mkdir -p news_classification_project/data/processed
!mkdir -p news_classification_project/models
!mkdir -p news_classification_project/results
!mkdir -p news_classification_project/src

!mv train.csv news_classification_project/data/raw/
!mv test.csv news_classification_project/data/raw/

!ls news_classification_project/data/raw

# Commented out IPython magic to ensure Python compatibility.
# %%writefile news_classification_project/src/data_preprocessing.py
# import re
# import nltk
# from nltk.corpus import stopwords
# 
# nltk.download("stopwords")
# 
# stop_words=set(stopwords.words("english"))
# 
# def clean_text(text):
#     text=text.lower()
#     text=re.sub(r'[^a-zA-Z]',' ',text)
#     words=text.split()
#     words=[w for w in words if w not in stop_words]
#     return " ".join(words)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile news_classification_project/src/feature_engineering.py
# 
# import pandas as pd
# from sklearn.feature_extraction.text import TfidfVectorizer
# 
# def create_features(data_path):
# 
#     df = pd.read_csv(data_path)
# 
#     X = df["clean_text"]
#     y = df["label"]
# 
#     vectorizer = TfidfVectorizer(max_features=5000)
# 
#     X_vec = vectorizer.fit_transform(X)
# 
#     return X_vec, y

# Commented out IPython magic to ensure Python compatibility.
# %%writefile news_classification_project/src/train.py
# 
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.svm import LinearSVC
# from sklearn.metrics import accuracy_score
# 
# def train_model(X,y):
# 
#     X_train,X_test,y_train,y_test=train_test_split(
#         X,y,test_size=0.2,random_state=42
#     )
# 
#     models={
#         "Logistic Regression":LogisticRegression(max_iter=1000),
#         "Naive Bayes":MultinomialNB(),
#         "Linear SVM":LinearSVC()
#     }
# 
#     best_model=None
#     best_acc=0
# 
#     for name,model in models.items():
# 
#         model.fit(X_train,y_train)
# 
#         pred=model.predict(X_test)
# 
#         acc=accuracy_score(y_test,pred)
# 
#         print(name,"Accuracy:",acc)
# 
#         if acc>best_acc:
#             best_acc=acc
#             best_model=model
# 
#     return best_model,X_test,y_test

# Commented out IPython magic to ensure Python compatibility.
# %%writefile news_classification_project/src/evaluate.py
# 
# from sklearn.metrics import accuracy_score
# 
# def evaluate_model(model,X_test,y_test):
# 
#     pred=model.predict(X_test)
# 
#     acc=accuracy_score(y_test,pred)
# 
#     print("\nFinal Model Accuracy:",acc)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile news_classification_project/main.py
# 
# import pandas as pd
# from src.data_preprocessing import clean_text
# from src.feature_engineering import create_features
# from src.train import train_model
# from src.evaluate import evaluate_model
# 
# print("NEWS ARTICLE CLASSIFICATION PIPELINE\n")
# 
# train=pd.read_csv("data/raw/train.csv")
# test=pd.read_csv("data/raw/test.csv")
# 
# train["text"]=train["Title"]+" "+train["Description"]
# test["text"]=test["Title"]+" "+test["Description"]
# 
# train=train[["text","Class Index"]]
# test=test[["text","Class Index"]]
# 
# train.columns=["text","label"]
# test.columns=["text","label"]
# 
# df=pd.concat([train,test])
# 
# df["clean_text"]=df["text"].apply(clean_text)
# 
# df.to_csv("data/processed/news_clean.csv",index=False)
# 
# X,y=create_features("data/processed/news_clean.csv")
# 
# model,X_test,y_test=train_model(X,y)
# 
# evaluate_model(model,X_test,y_test)

# Commented out IPython magic to ensure Python compatibility.
# %cd news_classification_project
!python main.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# pandas
# numpy
# scikit-learn
# nltk

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # News Article Classification using Machine Learning
# 
# ## Project Overview
# This project builds a machine learning pipeline to classify news articles into categories such as World, Sports, Business, and Sci/Tech.
# 
# ## Dataset
# AG News Dataset (Kaggle)
# 
# ## Folder Structure
# 
# news_classification_project
# │
# ├── data
# │   ├── raw
# │   └── processed
# ├── models
# ├── results
# ├── src
# ├── main.py
# ├── requirements.txt
# └── README.md
# 
# ## Steps to Run
# 
# pip install -r requirements.txt
# python main.py
# 
# ## Models Used
# Logistic Regression
# Naive Bayes
# Linear SVM
# 
# ## Result
# Best model: Logistic Regression
# Accuracy: ~90.8%

!zip -r news_classification_project.zip .